# -*- coding: utf-8 -*-
"""breast cancer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oKUHDYC7ce3iC_carXPPtlcM6EGKNf0q
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

df = pd.read_csv("/content/data1.csv")

df.head(20)

df.shape

df.info()

df.describe()

df.rename(index={"La1el":"Label"},inplace = True)

df.head()

df["Label"].value_counts()

df.groupby("Label").mean()

x = df.drop(columns = ["Label","diagnosis"],axis = 1)
y =  df["Label"]

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

model = LogisticRegression()

model.fit(x_train,y_train)

x_train_prediction = model.predict(x_train)
training_data_accuracy = accuracy_score(y_train,x_train_prediction)

print("Accuracy on training data =",training_data_accuracy)

x_test_prediction = model.predict(x_test)
test_data_accuracy = accuracy_score(y_test, x_test_prediction)

print('Accuracy on test data = ', test_data_accuracy)

input_data = (13.54,14.36,87.46,566.3,0.09779,0.08129,0.06664,0.04781,0.1885,0.05766,0.2699,0.7886,2.058,23.56,0.008462,0.0146,0.02387,0.01315,0.0198,0.0023,15.11,19.26,99.7,711.2,0.144,0.1773,0.239,0.1288,0.2977,0.07259)

input_data_as_numpy_array = np.asarray(input_data)

input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = model.predict(input_data_reshaped)

print(prediction)

if (prediction[0] == 0):
  print('The Breast cancer is Malignant')

else:
  print('The Breast Cancer is Benign')